support phpMyAdmin configuration storage settings
bitnami/bitnami-docker-phpmyadmin pull request #35
Opened 2021-11-30 14:17 UTC by LeonPoon

This is 2nd attempt. (First one is #34, closed because I didn't have time to respond to the latest suggestions...)

Solves #27.

A note about `create_tables.sql`, I would make a choice not to handle creating the tables here. Typically database side of things are set up outside of phpmyadmin setup. Other than this, I did:

* rename the env vars to start with `CONFIGURATION_STORAGE_` and gave some sane default values, and
* remove the need to code in a list of table names.

2021-12-01 09:16 UTC, migruiz4 requested changes
Hi @LeonPoon,

Thank you very much for your contribution! Please check my comment below.

2021-12-01 09:16 UTC, migruiz4 commented on 5/debian-10/rootfs/opt/bitnami/scripts/libphpmyadmin.sh
> +       ! is_empty_value "$CONFIGURATION_STORAGE_DATABASE_PMADB"; then
I think that ignoring everything if a single variable is missing may lead to confusion.

I would suggest adding a variable, e.g `CONFIGURATION_STORAGE_ENABLE` that made it easier to control:

```suggestion
    if is_boolean_yes "$CONFIGURATION_STORAGE_ENABLE"; then
```

Then, in the `phpmyadmin_validate`, add a section like this:
```bash
    if is_boolean_yes "$CONFIGURATION_STORAGE_ENABLE"; then
        for empty_env_var in "CONFIGURATION_STORAGE_DATABASE_CONTROLHOST" "CONFIGURATION_STORAGE_DATABASE_CONTROLPORT" "CONFIGURATION_STORAGE_DATABASE_CONTROLUSER" "CONFIGURATION_STORAGE_DATABASE_CONTROLPASS"
"CONFIGURATION_STORAGE_DATABASE_PMADB"; do
            is_empty_value "${!empty_env_var}" && print_validation_error "The ${empty_env_var} environment variable is empty or not set."
        done
  fi
```

2021-12-02 08:53 UTC, LeonPoon commented on 5/debian-10/rootfs/opt/bitnami/scripts/libphpmyadmin.sh
> +       ! is_empty_value "$CONFIGURATION_STORAGE_DATABASE_PMADB"; then
Done that. Please review.

2021-12-07 10:25 UTC, javsalgar approved these changes
LGTM

2021-12-09 10:31 UTC, merged

2021-12-09 11:24 UTC, juan131 commented
Hi @LeonPoon 

A new container was released including your changes (version `5.1.1-debian-10-r166`). Please note that some env. variables were renamed to follow the naming standards we usually follow, find more info in the commit below:

- https://github.com/bitnami/bitnami-docker-phpmyadmin/commit/8ba2a4ef723e5b280afcb30ab552ba6812ced01e