phpMyAdmin servers AllowDeny order/rules
bitnami/bitnami-docker-phpmyadmin pull request #37
Opened 2022-04-15 13:36 UTC by rowanruseler

Included the configuration of AllowDeny order/rules to be configured by
env variables. Included a small example within the README

Signed-off-by: Rowan Ruseler <rowanruseler@gmail.com>

2022-04-18 15:34 UTC, dgomezleon requested changes
Hi @rowanruseler ,

Thanks a lot for contributing.

I required some changes in order to follow our standards. Could you take a look?

Regards

2022-04-18 15:34 UTC, dgomezleon commented on 5/debian-10/rootfs/opt/bitnami/scripts/phpmyadmin-env.sh
> +export ALLOWDENY_RULES="${ALLOWDENY_RULES:-}"
```suggestion
export CONFIGURATION_ALLOWDENY_ORDER="${ALLOWDENY_ORDER:-}"
export CONFIGURATION_ALLOWDENY_RULES="${ALLOWDENY_RULES:-}"
```

2022-04-18 15:34 UTC, dgomezleon commented on 5/debian-10/rootfs/opt/bitnami/scripts/phpmyadmin-env.sh
> +    ALLOWDENY_RULES
```suggestion
    CONFIGURATION_ALLOWDENY_ORDER
    CONFIGURATION_ALLOWDENY_RULES
```

2022-04-18 15:34 UTC, dgomezleon commented on README.md
> +- `ALLOWDENY_RULES`: Allow or deny hosts/user to connect to the database. Value should be literal, e.g.: "array('deny bob from all')"
```suggestion
- `CONFIGURATION_ALLOWDENY_ORDER`: Set the AllowDeny order. Available values are: ``, `deny,allow`, `allow,deny`, `explicit`. No defaults.
- `CONFIGURATION_ALLOWDENY_RULES`: Array of strings to allow or deny hosts/user to connect to the database. The value must be literal, following the format `'allow' | 'deny' <username> [from] <ipmask>`. No defaults.
```

2022-04-18 15:34 UTC, dgomezleon commented on 5/debian-10/rootfs/opt/bitnami/scripts/libphpmyadmin.sh
> +
Remove the info since we are not using it for other parameters:
```suggestion
    ! is_empty_value "$CONFIGURATION_ALLOWDENY_ORDER" && phpmyadmin_conf_set "\$cfg['Servers'][\$i]['AllowDeny']['order']" "$ALLOWDENY_ORDER"
    ! is_empty_value "$CONFIGURATION_ALLOWDENY_RULES" && phpmyadmin_conf_set "\$cfg['Servers'][\$i]['AllowDeny']['rules']" "array($ALLOWDENY_RULES)" yes
```

Apart from that, you should validate `CONFIGURATION_ALLOWDENY_ORDER` with something like this: 

```
   if [[ -n "$CONFIGURATION_ALLOWDENY_ORDER" ]]; then
        if ! [[ "$CONFIGURATION_ALLOWDENY_ORDER" =~ ^(deny,allow|allow,deny|explicit)$ ]]; then
            print_validation_error "The allowed values for CONFIGURATION_ALLOWDENY_ORDER are: 'deny,allow', 'allow,deny', or 'explicit'."
        fi
    fi
```

2022-04-20 15:10 UTC, rowanruseler commented
@dgomezleon thank you for taking the time to checkout the PR, I made the adjustments as you suggested.

2022-04-20 16:45 UTC, dgomezleon commented
Thanks @rowanruseler ,

Could you please sign your latest commits to pass the DCO? Click on `Details` to check how to do it.

2022-04-20 16:54 UTC, rowanruseler commented
> Thanks @rowanruseler ,
> 
> Could you please sign your latest commits to pass the DCO? Click on `Details` to check how to do it.

I did sign the latest PR, not sure why it didn't take

2022-04-21 08:49 UTC, dgomezleon commented
No problem. It was due to the fact you apply my suggestions from the UI.

2022-04-21 08:51 UTC, dgomezleon requested changes
Just a minor change to avoid issues showing the README.

2022-04-21 08:51 UTC, dgomezleon commented on README.md
> +- `CONFIGURATION_ALLOWDENY_ORDER`: Set the AllowDeny order. Available values are: ``, `deny,allow`, `allow,deny`, `explicit`. No defaults.
To make it clearer and avoid renderization issues:
```suggestion
- `CONFIGURATION_ALLOWDENY_ORDER`: Set the AllowDeny order. If your rule order is empty, then IP authorization is disabled. Available values are: `deny,allow`, `allow,deny`, `explicit`. No defaults.
```

2022-04-21 10:22 UTC, dgomezleon approved these changes

2022-04-21 10:22 UTC, merged